travel/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
#new imports:
from flask_login import login_user, login_required, logout_user
from flask_bcrypt import generate_password_hash, check_password_hash
from .models import User
from . import db

#create a blueprint
authbp = Blueprint('auth', __name__ )

@authbp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form is fine, HTTP request is POST
    if (register.validate_on_submit()==True):
            #get username, password and email from the form
            uname = register.user_name.data
            pwd = register.password.data
            email = register.email_id.data
            #check if a user exists
            user = db.session.scalar(db.select(User).where(User.name==uname))
            if user:#this returns true when user is not None
                flash('Username already exists, please try another')
                return redirect(url_for('auth.register'))
            # don't store the password in plaintext!
            pwd_hash = generate_password_hash(pwd)
            #create a new User model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when the HTTP request calling this page is a GET
    else:
        return render_template('user.html', form=register, heading='Register')

@authbp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        user = db.session.scalar(db.select(User).where(User.name==user_name))
        #if there is no user with that name
        if user is None:
            error = 'Incorrect username'#could be a security risk to give this much info away
        #check the password - notice password hash function
        elif not check_password_hash(user.password_hash, password): # takes the hash and password
            error = 'Incorrect password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@authbp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

travel/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import Destination
from . import db

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    destinations = db.session.scalars(db.select(Destination)).all()    
    return render_template('index.html', destinations=destinations)

@mainbp.route('/search')
def search():
    search_term = request.args.get('search', '')

    if search_term:
        query = "%" + search_term + "%"
        destinations = db.session.execute(db.select(Destination).where(Destination.description.like(query)))
    else:
        destinations = db.session.execute(db.select(Destination))

    destinations = destinations.scalars().all()
    return render_template('index.html', destinations=destinations)

travel/templates/base.html
<html>

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>My Travel App</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
   <!-- Header -->
   <header class="bg-light border-bottom">

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container">

            <!-- Your Travel App Name or Logo -->
            <a href="/" class="navbar-brand">My Travel App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
               data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
               aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
               <div class="navbar-nav ml-auto">

                  <!-- Register/Login/Logout and welcome -->
                  {% if current_user.is_authenticated %}
                     <a class="nav-item nav-link disabled text-muted" href="#">Welcome {{current_user.name}}</a>
                     <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                  {% else %}
                     <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                     <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                  {% endif %}

                  <a class="nav-item nav-link" href="{{ url_for('destination.create') }}">Destinations</a>
                  <a class="nav-item nav-link" href="#">Bookings</a>
                  
               </div>
            </div>
         </div>
      </nav>
      <!-- flashes any messages to the user -->
      {% with messages = get_flashed_messages() %}
      {% if messages %} <!-- check if there are any messages -->
      <div class="container-fluid">
         <div class="row mt-3 mb-3">
            <div class="col-md-12">
            {% for message in messages %} <!--loop through the messages-->
            <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
            {% endfor %}
         </div>
      </div>
      </div>
      {% endif %}
      {% endwith %}
    
      {% block header %}

      {% endblock %}

   </header>
      
   {% block content %}

   {% endblock %}
   
    <footer class="footer">
        <div class="text-center py-2 bg-light">
            <span class="text-dark">Copyright &copy; {{ year }}</span>
        </div>
    </footer> 
   </body>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</html>

travel/templates/index.html
{% extends 'base.html' %}

{% block header %}
      <!--Jumbotron-->
      <div class="container">
         <div class="row justify-content-center mt-5 pb-4">
            <div class="col-md-8">
               <div class="card shadow p-5 mb-5" style="background-color: rgb(247, 252, 255);">
                  <h1 class="text-center mb-3">Find our best travel deals</h1>

                  <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}" >
                     <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm">
                     <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
                   </form>
                  
               </div>
            </div>
         </div>
      </div>
{% endblock %}

{% block content %}   
      <div class="container">
         <div class="row mt-5 mb-5 justify-content-center">
            <div class="col-md-10">
               <div class="media border p-3 d-flex justify-content-start">
                  <img class="align-self-center me-3" style="max-width:120px"
                     src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Earth_Western_Hemisphere_transparent_background.png/600px-Earth_Western_Hemisphere_transparent_background.png"
                     alt="Planet Earth">
                  <div class="align-self-center media-body">
                     <h5 class="mt-0">Find the best destinations on earth</h5>
                     <p class="d-none d-sm-block">Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                        scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra
                        turpis. Fusce condimentum nunc ac nisi vulputate fringilla.</p>
                     <a href="/register" class="btn btn-primary">Join Now</a>
                  </div>
               </div>
            </div>
         </div>

         <style>
            .card-img-top{
               max-width: 100%;
               max-height: 100%;
               width: auto;
               height: auto;
            }
         </style>

         <div class="card-group">
            {% for destination in destinations %}
            <div class="card col-lg-4 col-md-6 mb-4" style="padding: 10px;">
               <img class="card-img-top"
                  src="{{ destination.image }}" alt="destination picture">
               <div class="card-body">
                  <h5 class="card-title">{{ destination.name }}</h5>
                  <p class="card-text">{{ destination.description }}</p>
               </div>
               <div class="card-footer"><a href="{{ url_for('destination.show', id=destination.id) }}" class ="btn btn-primary"> View Details </a></div>
            </div>
            {% endfor %}
         </div>
      </div>
{% endblock %}

travel/templates/user.html
{% extends 'base.html' %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="display-4">{{ heading }}</h1>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-6 offset-md-3">
            {{ render_form(form) }}
        </div>
    </div>
</div>
{% endblock %}